### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by CyrilleB79** [jscholes/nvda-speech-history#25]
## Context

I was running NVDA 2019.3.1 for test purpose only.

## Issue

When I run NVDA 2019.3.1 (temp copy) with Speech History, I get the following error at startup or when add-on are reloaded with NVDA+ctrl+F3.

```
ERROR - globalPluginHandler.listPlugins (22:26:48.915) - MainThread (12048):
Error importing global plugin speechHistory
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\speechHistory\globalPlugins\speechHistory.py", line 13, in <module>
    from eventHandler import FocusLossCancellableSpeechCommand
ImportError: cannot import name 'FocusLossCancellableSpeechCommand' from 'eventHandler' (C:\Users\Cyrille\AppData\Local\Temp\nsz6CE5.tmp\app\library.zip\eventHandler.pyc)
```

## Solution

Change the compatibility version in the manifest or fix this issue for NVDA 2019.3.1.

**Comment by CyrilleB79** [comment]
@jscholes thanks for releasing 2022.1.
However this issue is still present.
I do not know if it is easy or not to fix the issue for NVDA 2019.3.1.
But at least, reducing the compatibility range should be trivial.
Could you take care of it for next version?
Thanks.
